In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('dataset/census/census-income.data', header=None,delimiter=',')
test=pd.read_csv('dataset/census/census-income.test', header=None,delimiter=',')
print(data.shape)
print(test.shape)

(199523, 42)
(99762, 42)

In [3]:
from ucimlrepo import fetch_ucirepo 
census_income_kdd = fetch_ucirepo(id=117)

### Create headers

In [4]:
with open('dataset/headers.txt', 'r') as f:
    lines = f.readlines()
description=[]
for line in lines:
    description.append(line.split('(')[1].split(')')[0].strip())
description.insert(24,'instance weight')
description[-1]="94 or 95"
description.append('below or above $50k')
description[37]="fill inc questionaire for veteran's admin"
description[19]="tax filer status"
description[7]="marital status"
description[6]="enrolled in edu last week"
description[2]="industry code"
description[3]="occupation code"
description=pd.DataFrame({'description':description})
description

                                  description
0                                         age
1                             class of worker
2                               industry code
3                             occupation code
4                                   education
5                               wage per hour
6                   enrolled in edu last week
7                              marital status
8                         major industry code
9                       major occupation code
10                                       race
11                            hispanic origin
12                                        sex
13                    member of a labor union
14                    reason for unemployment
15          full or part time employment stat
16                              capital gains
17                             capital losses
18                      dividends from stocks
19                           tax filer status
20               region of previous residence
21                state of previous residence
22         detailed household and family stat
23    detailed household summary in household
24                            instance weight
25               migration code-change in msa
26               migration code-change in reg
27             migration code-move within reg
28              live in this house 1 year ago
29              migration prev res in sunbelt
30            num persons worked for employer
31                    family members under 18
32                    country of birth father
33                    country of birth mother
34                      country of birth self
35                                citizenship
36              own business or self employed
37  fill inc questionaire for veteran's admin
38                          veterans benefits
39                       weeks worked in year
40                                   94 or 95
41                        below or above $50k

In [6]:
data.columns=description['description']
data.head()
data.to_csv("train.csv")
test.columns=description['description']
test.to_csv("test.csv")

In [7]:
df=census_income_kdd.variables
df

,name,role,type,demographic,description,units,missing_values
0,AAGE,Feature,Integer,Age,age,None,no
1,ACLSWKR,Feature,Categorical,None,class of worker,None,no
2,ADTINK,Feature,Integer,None,industry code,None,no
3,ADTOCC,Feature,Integer,Occupation,occupation code,None,no
4,AHGA,Feature,Integer,Education Level,education,None,no
5,AHSCOL,Feature,Categorical,Education Level,enrolled in edu last week,None,no
6,AMARITL,Feature,Categorical,Marital Status,marital status,None,no
7,AMJIND,Feature,Categorical,None,major industry code,None,no
8,AMJOCC,Feature,Categorical,Occupation,major occupation code,None,no
9,ARACE,Feature,Categorical,Race,race,None,no
10,AREORGN,Feature,Categorical,None,hispanic origin,None,no
11,ASEX,Feature,Categorical,Sex,sex,None,no
12,AUNMEM,Feature,Categorical,None,member of a labor union,None,no
13,AUNTYPE,Feature,Categorical,None,reason for unemployment,None,no
14,AWKSTAT,Feature,Integer,None,full or part time employment stat,None,no
15,CAPGAIN,Feature,Integer,None,capital gains,None,no
16,GAPLOSS,Feature,Integer,None,capital losses,None,no
17,DIVVAL,Feature,Categorical,None,dividends from stocks,None,no
18,FILESTAT,Feature,Categorical,None,tax filer status,None,no
19,GRINREG,Feature,Categorical,None,region of previous residence,None,no
20,GRINST,Feature,Categorical,None,state of previous residence,None,no
21,HHDFMX,Feature,Continuous,Other,detailed household and family stat,None,no
22,HHDREL,Feature,Categorical,None,detailed household summary in household,None,no
23,MARSUPWRT,Feature,Categorical,None,instance weight,None,no
24,MIGMTR1,Feature,Categorical,None,migration code-change in msa,None,yes
25,MIGMTR3,Feature,Categorical,None,migration code-change in reg,None,yes
26,MIGMTR4,Feature,Categorical,None,migration code-move within reg,None,yes
27,MIGSAME,Feature,Integer,None,live in this house 1 year ago,None,no
28,MIGSUN,Feature,Categorical,None,migration prev res in sunbelt,None,yes
29,NOEMP,Feature,Categorical,None,num persons worked for employer,None,no
30,PARENT,Feature,Categorical,None,family members under 18,None,no
31,PEFNTVTY,Feature,Categorical,None,country of birth father,None,yes
32,PEMNTVTY,Feature,Integer,None,country of birth mother,None,yes
33,PENATVTY,Feature,Categorical,Nationality,country of birth self,None,no
34,PRCITSHP,Feature,Integer,None,citizenship,None,no
35,SEOTR,Feature,Integer,None,own business or self employed,None,no
36,VETQVA,Feature,Categorical,None,fill inc questionaire for veteran's admin,None,no
37,VETYN,Feature,Categorical,None,veterans benefits,None,no
38,WKSWORK,Feature,Categorical,None,weeks worked in year,None,no
39,income,Target,Binary,Income,below or above $50k,None,no
40,AHRSPAY,Feature,Integer,None,wage per hour,None,no
41,year,Feature,Integer,None,94 or 95,None,no

In [8]:
df=census_income_kdd.variables
df = df.set_index('description').reindex(description['description']).reset_index()
df.to_csv("variables.csv")